#!/bin/bash
echo "Stopping container"
sudo docker stop laravel_app laravel_db
echo "Remove container"
sudo docker rm laravel_app laravel_db
echo "Delete file"
sudo rm -rf Dockerfile
sudo rm -rf laravel_*

